# Generated by Django 2.2.7 on 2019-12-10 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=140)),
                ('email', models.EmailField(max_length=254)),
                ('assunto', models.CharField(max_length=30)),
                ('messagem', models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='cadastro',
            name='login',
            field=models.CharField(default='1111', max_length=15),
        ),
        migrations.AddField(
            model_name='cadastro',
            name='senha',
            field=models.CharField(default='1111', max_length=15),
        ),
    ]
